# Sets as `se01` or `sa01` 'pm01'
sign:
  - [1, 1, -1, -1, -1, -1]
  - [-1, 1, -1, 1, -1, -1]
  - [1]
  - [1, -1, -1, 1, -1]
  - [-1, -1, -1, -1, -1]
  - [1]
default_position_offset:
  - [0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0]
  - [0]
  - [0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0]
  - [0]

minimum_stiffness:
  - [0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0]
  - [0]
  - [0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0]
  - [0]
minimum_damping:
  - [0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0]
  - [0]
  - [0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0]
  - [0]
